config/routes.rb
Rails.application.routes.draw do
  root to: 'tops#index'
  get 'tops' => 'tops#about'
  devise_for :users
  resources :users,only:[:index, :show, :edit, :update]
  resources :books,only:[:index, :show, :edit,:create,:update]
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    validates :title,presence: true
    validates :body,presence: true,length: {maximum: 199 }
    belongs_to :user 
end

app/models/post_image.rb
class PostImage < ApplicationRecord
    belongs_to :user
    attachment :image
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name,presence: true,length:{minimum:2,maximum:20 }
  validates :introduction,length:{maximum:50}
  attachment :profile_image
  has_many :books,dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  def after_sign_in_path_for(resource)
    if current_user
      flash[:notice] = 'Signed in successfully' 
      user_path(current_user)
    else
      flash[:notice] = 'Welcome! You have signed up successfully.'
      user_path(current_user)
    end
  end
  def after_sign_out_path_for(resource)
    flash[:notice] = 'Signed out successfully.' 
    root_path
  end 

protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :correct_book, only: [:edit, :update]
  def index
    @book = Book.new
    @books = Book.all
  end

  def show
    @booknew = Book.new
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end
  
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id)
      flash[:notice] = "successfully"
    else
      @books = Book.all
      render 'index'
    end
  end 

  def destroy
    book = Book.find(params[:id])
    book.destroy
    flash[:notice] = "successfully"
    redirect_to books_path
  end

  def update
    @book = Book.find(params[:id])
    if @book.update_attributes(book_params)
      redirect_to book_path
      flash[:notice] = "successfully"
    else
      render 'edit'
    end
  end


private
def correct_book
  book = Book.find(params[:id])
  if current_user != book.user
    redirect_to user_path(current_user)
  end
end
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
    def index
    end
    def about
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]
  def index
    @booknew = Book.new
    @users = User.all
  end

  def show
    @booknew = Book.new
    @user = User.find(params[:id])
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to user_path(@user.id)
      flash[:notice] = "successfully"
    else
      render 'edit'
    end
  end
private
  def correct_user
    user = User.find(params[:id])
    if current_user != user
      redirect_to user_path(current_user)
    end
  end
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<% if @book.errors.any? %>
<div id="error_explanation" class="alert alert-danger">
  <% @book.errors.full_messages.each do |message| %>
    <ul>
      <li>
        error<%= message %>
      </li>
    </ul>
  <% end %>
</div>
<% end %>
<%= form_for(@book) do |f| %>
  <p><%= f.text_field :title, autofocus: true,placeholder:"タイトル"%></p>
  <p><%= f.text_area :body, autofocus: true,placeholder:"本文"%></p>
  <%= f.submit "変更を保存" %>
<% end %>
<%= link_to 'show',book_path %>
<%= link_to 'back',books_path %>

app/views/books/index.html.erb
<% flash[:notice] %>
<% if @book.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li>error<%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= attachment_image_tag current_user, :profile_image,size: "100x100" %>
<p>名前</p>
<p><%= current_user.name %></p>
<p>自己紹介</p>
<p><%= current_user.introduction %></p>
<%= link_to 'プロフィール編集' ,edit_user_path(current_user.id) %>
<hr>
<%= form_for(@book) do |f| %>
  <div class="field row">
    <label for="book_title">Title</label>
    <%= f.text_field :title,class:"col-xs-12 book_title" %>
  </div>
  <div class="field row">
    <label for="book_opinion">Opinion</label>
    <%= f.text_area :body,class:"col-xs-12 book_body" %><br />
  </div>
  <div class="actions row">
    <%= f.submit 'Create Book',class:"btn btn-primary col-xs-12" %>
  </div>
<% end %>
<h1>投稿一覧ページ</h1>
<% @books.each do |book| %>
  <%= link_to user_path(book.user) do %>
    <%= attachment_image_tag book.user, :profile_image,size: "100x100" %><br>
  <% end %>
  <%= link_to book_path(book) do %>
    <%= book.title %><br>
  <% end %>
  <%= book.body %><br>
  <hr>
<% end %>

app/views/books/show.html.erb
<%= attachment_image_tag @book.user, :profile_image,size: "100x100" %>
<p>名前</p>
<p><%= @book.user.name %></p>
<p>自己紹介</p>
<p><%= @book.user.introduction %></p>
<%= link_to 'プロフィール編集' ,edit_user_path(current_user) %>
<hr>
<%= link_to user_path(@book.user.id) do  %>
  <%= attachment_image_tag @book.user, :profile_image,size: "100x100" %>
  <%= @book.user.name %>
<% end %>
<p><%= @book.title %></p>
<p><%= @book.body %></p>
<%= link_to "編集",edit_book_path %>
<%= link_to "削除",destroy_book_path(@book.id),method: :delete %>
<hr>
<%= form_for @booknew do |f| %>
    <div class="field row">
      <label for="book_title">Title</label>
      <%= f.text_field :title,class:"col-xs-12 book_title" %>
    </div>
    <div class="field row">
      <label for="book_opinion">Opinion</label>
      <%= f.text_area :body,class:"col-xs-12 book_body" %><br />
    </div>
    <div class="actions row">
      <%= f.submit 'Create Book',class:"btn btn-primary col-xs-12" %>
    </div>
  <% end %>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2Contenue</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if user_signed_in? %>
    <nav>
      <ul>
        <li><%= link_to 'home',user_path(current_user.id) %></li>
        <li><%= link_to 'users',users_path %></li>
        <li><%= link_to 'books',books_path %></li>
        <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
      </ul>
    </nav>
    <% else %>
      <nav>
        <ul>
          <li><%= link_to 'home',root_path %></li>
          <li><%= link_to 'show',tops_path %></li>
          <li><%= link_to 'login',new_user_session_path %></li>
          <li><%= link_to 'sign up',new_user_registration_path %></li>
        </ul>
      </nav>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/tops/about.html.erb
<p>無意味なページ</p>

app/views/tops/index.html.erb
<%= flash[:notice] %>
<h1>Topページ</h1>
<p>Please sign in or sign up</p>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
<div id="error_explanation" class="alert alert-danger">
  <% @user.errors.full_messages.each do |message| %>
    <ul>
      <li>
        error<%= message %>
      </li>
    </ul>
  <% end %>
</div>
<% end %>
<%= form_for(@user) do |f| %>
  <p><%= attachment_image_tag @user, :profile_image,size: "100x100" %></p>
  <p><%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %></p>
  <p><%= f.text_field :name, autofocus: true,placeholder:"名前"%></p>
  <p><%= f.text_area :introduction, autofocus: true,placeholder:"自己紹介"%></p>
  <%= f.submit "変更を保存" %>
<% end %>

app/views/users/index.html.erb
<%= flash[:notice] %>
<h1>作成したユーザ一覧のページ</h1>
<%= attachment_image_tag current_user, :profile_image,size: "100x100" %>
<p>名前</p>
<p><%= current_user.name %></p>
<p>自己紹介</p>
<p><%= current_user.introduction %></p>
<%= link_to 'プロフィール編集' ,edit_user_path(current_user.id) %>
<h2>作成したユーザ</h2>
<% @users.each do |users| %>
  <%= attachment_image_tag users, :profile_image,size: "100x100" %>
  <p><%= users.name %></p>
  <%= link_to 'show',user_path(users.id) %><br>
<% end %>
<%= form_for @booknew do |f| %>
  <div class="field row">
    <label for="book_title">Title</label>
    <%= f.text_field :title,class:"col-xs-12 book_title" %>
  </div>
  <div class="field row">
    <label for="book_opinion">Opinion</label>
    <%= f.text_area :body,class:"col-xs-12 book_body" %><br />
  </div>
  <div class="actions row">
    <%= f.submit 'Create Book',class:"btn btn-primary col-xs-12" %>
  </div>
<% end %>

app/views/users/show.html.erb
<%= flash[:notice] %>
<h1><%= @user.name %>のMYページ</h1>
<%= attachment_image_tag @user, :profile_image,size: "100x100" %>
<p>名前</p>
<p><%= @user.name %></p>
<p>自己紹介</p>
<p><%= @user.introduction %></p>
<% if current_user.id == @user.id %>
  <%= link_to 'プロフィール編集' ,edit_user_path(@user) %>
<% end %>
<%= form_for @booknew do |f| %>
  <div class="field row">
    <label for="book_title">Title</label>
    <%= f.text_field :title,class:"col-xs-12 book_title" %>
  </div>
  <div class="field row">
    <label for="book_opinion">Opinion</label>
    <%= f.text_area :body,class:"col-xs-12 book_body" %><br />
  </div>
  <div class="actions row">
    <%= f.submit 'Create Book',class:"btn btn-primary col-xs-12" %>
  </div>
<% end %>
<h2>投稿データ</h2>
<% @books.each do |book| %>
  <%= attachment_image_tag book.user, :profile_image,size: "100x100" %><br>
  <%= link_to book_path(book.id) do %>
    <%= book.title %><br>
  <% end %>
  <%= book.body %><br>
  <hr>
<% end %>
